### ISSUE TITLE
@iterate

### ISSUE THREAD

**Issue by tmjoen** [twined/europa#21]
For instance:

```css
body {
  @each $bp-name, $bp-size in $grid-breakpoints {
    @responsive >=#{$bp-name} {
      padding-top: map-get($fixed-menu-compensation-padding, $bp-name);
    }
  }
}
```

```postcss
body {
  @iterate theme.fixedMenu.padding.y {
    @responsive $key {
      padding-top: $value;
    }
  }
}
```

```scss
article {
  @space margin-bottom xl;
  @column 6/12;
  @each $bp-name, $bp-size in $grid-breakpoints {
    margin-left: map-get($container-padding, $bp-name) * -1;
  }
}
```

```postcss
article {
  @iterate theme.container.padding {
    @responsive $key {
      margin-left: calc($value/2);
    }
  }
}
```
