### ISSUE TITLE
@column-typography

### ISSUE THREAD

**Issue by tmjoen** [twined/europa#9]
### @column-typography
```postcss
@column-typography 4/5;
// sets 4/5 width with standard padding per breakpoint
```
- [x] implemented

```postcss
@column-typography 1/3 xs;
// sets 1/3 width with standard padding for XS breakpoint
```
- [x] implemented

```scss
@mixin col-typo($cols, $size: 0) {
  $percentage: percentage($cols / 12);
  @if $size > 1 {
    $size: $size / 10
  } @else {
    $size: 0
  }

  position: relative;
  flex: 0 0 $percentage;
  max-width: $percentage;
  padding-right: $percentage / 10 * (1 + $size);
}
```
